//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.DataProvider.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMA
    {
        public int OBJECTID { get; set; }
        public string MADMA { get; set; }
        public string TENDMA { get; set; }
        public string MoTa { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<decimal> TiLeThatThoat { get; set; }
        public string Nam { get; set; }
        public string Ky { get; set; }
    }
}
