//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.DataProvider.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONGHOKHACHHANG
    {
        public int OBJECTID { get; set; }
        public Nullable<short> TIEUCHUAN { get; set; }
        public Nullable<int> NAMSANXUAT { get; set; }
        public Nullable<int> SOTHANDONGHO { get; set; }
        public string VITRILAPDAT { get; set; }
        public Nullable<short> TINHTRANG { get; set; }
        public Nullable<decimal> APLUC { get; set; }
        public string DONVITHICONG { get; set; }
        public string DONVITHIETKE { get; set; }
        public string DBDONGHONUOC { get; set; }
        public string TENTHUEBAO { get; set; }
        public string SONHA { get; set; }
        public string MADUONG { get; set; }
        public string MAPHUONG { get; set; }
        public string MAQUAN { get; set; }
        public string GHICHU { get; set; }
        public Nullable<short> CODONGHO { get; set; }
        public string SOHOPDONG { get; set; }
        public Nullable<short> MUCDICHSUDUNG { get; set; }
        public Nullable<int> SONGUOISUDUNG { get; set; }
        public string MASOCHI { get; set; }
        public string SODIENTHOAI { get; set; }
        public string SONHACU { get; set; }
        public string MASOCHIMATSO { get; set; }
        public string CHIKHOAGOC { get; set; }
        public string SOCNKIEMDINH { get; set; }
        public Nullable<short> TINHTRANGQLDHN { get; set; }
        public Nullable<short> TINHTRANGTHUNGANDHN { get; set; }
        public Nullable<short> TINHTRANGTUBODHN { get; set; }
        public string SOHOKHAU { get; set; }
        public string TENTHUEBAOCU { get; set; }
        public string NGAYBAMCHI { get; set; }
        public string LYDOBAMCHI { get; set; }
        public string SOLANTHAY { get; set; }
        public string TRANGTHAI { get; set; }
        public Nullable<short> CAPCHINHXAC { get; set; }
        public Nullable<System.DateTime> NGAYLAPDAT { get; set; }
        public Nullable<System.DateTime> NGAYKIEMDINH { get; set; }
        public Nullable<short> NHAKIEMDINH { get; set; }
        public Nullable<decimal> DINHMUCSUDUNG { get; set; }
        public Nullable<System.DateTime> NGAYTHAYMOI { get; set; }
        public Nullable<int> THOIHANSUDUNG { get; set; }
        public Nullable<short> LOAIDONGHO { get; set; }
        public Nullable<short> HIEUDONGHO { get; set; }
        public string NGUOICAPNHAT { get; set; }
        public Nullable<System.DateTime> NGAYCAPNHAT { get; set; }
        public string MADMA { get; set; }
        public string MADMZ { get; set; }
        public string MAVAN { get; set; }
        public Nullable<short> TINHTRANGVAN { get; set; }
        public string COCHIAKHOA { get; set; }
        public string GHICHUVANKH { get; set; }
        public string KHUPHO { get; set; }
        public string SOHOSO { get; set; }
        public Nullable<short> LOAIVAN { get; set; }
        public string TENDUONG { get; set; }
        public Nullable<short> LOAIKHACHHANG { get; set; }
        public Nullable<short> LOAIMATSO { get; set; }
        public Nullable<decimal> GIABIEU { get; set; }
        public Nullable<System.DateTime> NGAYDOCSO { get; set; }
        public string MALOTRINH { get; set; }
        public string CHUKYDOCSO { get; set; }
        public string SOCHUNGMINH { get; set; }
        public Nullable<short> TINHTRANGKYTHUAT { get; set; }
        public Nullable<short> VITRI { get; set; }
        public string ThongTinSuaChua { get; set; }
        public string GHICHUTHONGTIN { get; set; }
        public string IDTHUA { get; set; }
        public Nullable<short> TINHTRANGDH { get; set; }
        public string CSTTThangGanNhat { get; set; }
        public string NHANVIENTHIETKE { get; set; }
        public string NHANVIENBAMCHI { get; set; }
        public Nullable<short> TINHTRANGVIPHAM { get; set; }
        public Nullable<short> TTRoRiTrenDHN { get; set; }
        public string DacDiemRoRi { get; set; }
        public Nullable<short> TinhTrangRoRi { get; set; }
        public Nullable<decimal> SLTieuThuTB { get; set; }
        public Nullable<short> TINHTRANGSUDUNG { get; set; }
        public Nullable<decimal> DOSAU { get; set; }
        public Nullable<short> COONGNGANH { get; set; }
        public Nullable<short> VATLIEU { get; set; }
        public Nullable<decimal> CHIEUDAI { get; set; }
        public Nullable<short> HIEU { get; set; }
        public string LOAIFILE { get; set; }
        public string IDHanhChinh { get; set; }
        public string MaHuyen { get; set; }
        public Nullable<short> Enabled { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<System.DateTime> NGAYTHEMMOI { get; set; }
    }
}
