//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.DataProvider.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANHCHINH
    {
        public int OBJECTID { get; set; }
        public string IDHanhChinh { get; set; }
        public string TenHanhChinh { get; set; }
        public Nullable<decimal> DienTich { get; set; }
        public string MaHuyen { get; set; }
        public string TenQuan { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
    }
}
