
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI.DataProvider.EF
{

using System;
    using System.Collections.Generic;
    
public partial class HOSOVATTUSUCO
{

    public Nullable<decimal> SoLuong { get; set; }

    public int RID { get; set; }

    public string IDSuCo { get; set; }

    public string MaVatTu { get; set; }

}

}
