//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.DataProvider.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoggerDMA
    {
        public long ID { get; set; }
        public string MaDMA { get; set; }
        public string TenDMA { get; set; }
        public string SiteID { get; set; }
    }
}
