//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.DataProvider.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LoggerEntities : DbContext
    {
        public LoggerEntities()
            : base("name=LoggerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LoggerDMA> LoggerDMAs { get; set; }
        public virtual DbSet<t_Channel_Configurations> t_Channel_Configurations { get; set; }
    
        public virtual ObjectResult<ApLucChiTietDMA_Result> ApLucChiTietDMA(string dMA, string tuNgay, string denNgay)
        {
            var dMAParameter = dMA != null ?
                new ObjectParameter("DMA", dMA) :
                new ObjectParameter("DMA", typeof(string));
    
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ApLucChiTietDMA_Result>("ApLucChiTietDMA", dMAParameter, tuNgayParameter, denNgayParameter);
        }
    
        public virtual ObjectResult<LuuLuongChiTietDMA_Result> LuuLuongChiTietDMA(string dMA, string tuNgay, string denNgay)
        {
            var dMAParameter = dMA != null ?
                new ObjectParameter("DMA", dMA) :
                new ObjectParameter("DMA", typeof(string));
    
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LuuLuongChiTietDMA_Result>("LuuLuongChiTietDMA", dMAParameter, tuNgayParameter, denNgayParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> SanLuongDMA(string dMA, string tuNgay, string denNgay)
        {
            var dMAParameter = dMA != null ?
                new ObjectParameter("DMA", dMA) :
                new ObjectParameter("DMA", typeof(string));
    
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("SanLuongDMA", dMAParameter, tuNgayParameter, denNgayParameter);
        }
    
        public virtual int TongSanLuongDMA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TongSanLuongDMA");
        }
    }
}
