//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.DataProvider.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBKHACHHANGMATNUOC
    {
        public int OBJECTID { get; set; }
        public string DBDONGHONUOC { get; set; }
        public string TENTHUEBAO { get; set; }
        public string SONHA { get; set; }
        public string MADUONG { get; set; }
        public string MAPHUONG { get; set; }
        public string MAQUAN { get; set; }
        public Nullable<short> CODONGHO { get; set; }
        public string SODIENTHOAI { get; set; }
        public string TENDMA { get; set; }
        public string TENDUONG { get; set; }
        public Nullable<System.DateTime> NGAYCAPNHAT { get; set; }
        public string OBJECTID_KH { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
    }
}
